"""Configuration for Janda textbook extraction."""

# Chapter definitions from Table of Contents
# Source: Applications of No-Limit Hold'em by Matthew Janda
JANDA_CHAPTERS = [
    {"name": "The Basics", "part": 1, "start": 18, "end": 44},
    {"name": "Preflop Play", "part": 2, "start": 46, "end": 102},
    {"name": "Post-flop Bet Sizing", "part": 3, "start": 104, "end": 111},
    {"name": "Flop Play IP", "part": 4, "start": 112, "end": 154},
    {"name": "Flop Play OOP", "part": 5, "start": 156, "end": 191},
    {"name": "Flop Play Special", "part": 6, "start": 193, "end": 237},
    {"name": "3-Bet Pots Flop", "part": 7, "start": 239, "end": 254},
    {"name": "Turn Play IP", "part": 8, "start": 257, "end": 290},
    {"name": "Turn Play OOP", "part": 9, "start": 293, "end": 318},
    {"name": "3-Bet Pots Turn", "part": 10, "start": 320, "end": 338},
    {"name": "River Play", "part": 11, "start": 340, "end": 373},
    {"name": "Multiway Pots", "part": 12, "start": 376, "end": 388},
    {"name": "Stack Depth", "part": 13, "start": 390, "end": 404},
    {"name": "Bet Sizing", "part": 14, "start": 406, "end": 423},
    {"name": "Applying Theory", "part": 15, "start": 426, "end": 433},
    {"name": "Sample Hands", "part": 16, "start": 435, "end": 492},
]

# Metadata schema for tagging chunks
METADATA_SCHEMA = {
    "streets": ["preflop", "flop", "turn", "river"],
    "board_textures": [
        "dry",
        "wet",
        "monotone",
        "two-tone",
        "rainbow",
        "paired",
        "connected",
        "disconnected",
        "high",
        "low",
        "middling",
    ],
    "pot_types": [
        "single_raised",
        "3-bet",
        "4-bet",
        "limped",
        "multiway",
        "heads_up",
    ],
    "positions": [
        "IP",
        "OOP",
        "BB",
        "SB",
        "BTN",
        "CO",
        "HJ",
        "UTG",
        "EP",
        "MP",
        "LP",
    ],
    "concepts": [
        "c-betting",
        "range_advantage",
        "equity_denial",
        "pot_control",
        "value_betting",
        "bluffing",
        "check_raising",
        "donk_betting",
        "floating",
        "semi_bluffing",
        "polarization",
        "linear_range",
        "merged_range",
        "board_coverage",
        "nut_advantage",
        "blockers",
        "reverse_implied_odds",
        "implied_odds",
        "pot_odds",
        "fold_equity",
        "protection",
        "thin_value",
        "over_betting",
        "under_betting",
        "delayed_cbet",
        "probe_betting",
        "continuation_betting",
        "barrel_strategy",
        "turn_check_back",
        "river_decision",
        "showdown_value",
        "range_construction",
        "balance",
        "exploitation",
        "gto_concepts",
        "frequency",
        "mixed_strategy",
        "indifference",
    ],
    "stack_depths": [
        "shallow",
        "medium",
        "deep",
        "100bb",
        "150bb+",
    ],
}

# Default PDF path
DEFAULT_PDF_PATH = "/Users/davideyal/Downloads/AplicationsofNLH (1).pdf"
